version: "3.8"

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: multimatics-backend
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Tniabri12
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Mount SQL script

  flask-app:
    build: .
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      POSTGRES_DB: multimatics-backend
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Tniabri12

volumes:
  postgres_data:
